# NumPy Basics: Arrays and Vectorized Computation

In [3]:
import numpy as np
np.random.seed(12345)
import matplotlib.pyplot as plt
plt.rc("figure", figsize=(10, 6))
np.set_printoptions(precision=4, suppress=True)

In [4]:
import numpy as np

my_arr = np.arange(1_000_000)
my_list = list(range(1_000_000))

%timeit my_arr2 = my_arr * 2
%timeit my_list2 = [x * 2 for x in my_list]

1.59 ms ± 18.7 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
75.7 ms ± 730 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [7]:
import numpy as np
data = np.array([[1.5, -0.1, 3], [0, -3, 6.5]])
print(data)
print()
print(data * 10)
print()
print(data + data)
print()
print(data.shape) 
print()
print(data.dtype)

[[ 1.5 -0.1  3. ]
 [ 0.  -3.   6.5]]

[[ 15.  -1.  30.]
 [  0. -30.  65.]]

[[ 3.  -0.2  6. ]
 [ 0.  -6.  13. ]]

(2, 3)

float64


In [11]:
data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1)
print(arr1)

data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)
print(arr2)
print()
print(arr2.ndim, arr2.shape)
print(arr1.dtype, arr2.dtype)

[6.  7.5 8.  0.  1. ]
[[1 2 3 4]
 [5 6 7 8]]

2 (2, 4)
float64 int64


In [19]:
np.zeros(10)
np.zeros((3, 6))
em = np.empty((2, 3, 2))

print(em[1][2] is None)

np.arange(15)

False


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [21]:
arr1 = np.array([1, 2, 3], dtype=np.float64)
arr2 = np.array([1, 2, 3], dtype=np.int32)
print(arr1.dtype, arr2.dtype)

arr = np.array([1, 2, 3, 4, 5])
print(arr.dtype)
float_arr = arr.astype(np.float64)
print(float_arr)
print(float_arr.dtype)

float64 int32
int64
[1. 2. 3. 4. 5.]
float64


In [23]:
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])
print(arr)
arr.astype(np.int32)

[ 3.7 -1.2 -2.6  0.5 12.9 10.1]


array([ 3, -1, -2,  0, 12, 10], dtype=int32)

In [24]:
numeric_strings = np.array(["1.25", "-9.6", "42"], dtype=np.string_)
numeric_strings.astype(float)

array([ 1.25, -9.6 , 42.  ])

In [25]:
int_array = np.arange(10)
calibers = np.array([.22, .270, .357, .380, .44, .50], dtype=np.float64)
int_array.astype(calibers.dtype)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [26]:
zeros_uint32 = np.zeros(8, dtype="u4")
zeros_uint32

array([0, 0, 0, 0, 0, 0, 0, 0], dtype=uint32)

In [28]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])
print(arr)
print(arr * arr)
print(arr - arr)
print(1 / arr)
print(arr ** 2)

[[1. 2. 3.]
 [4. 5. 6.]]
[[ 1.  4.  9.]
 [16. 25. 36.]]
[[0. 0. 0.]
 [0. 0. 0.]]
[[1.     0.5    0.3333]
 [0.25   0.2    0.1667]]
[[ 1.  4.  9.]
 [16. 25. 36.]]


In [30]:
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])
print(arr2)
arr2 > arr

[[ 0.  4.  1.]
 [ 7.  2. 12.]]


array([[False,  True, False],
       [ True, False,  True]])

In [38]:
arr = np.arange(10)
print(arr)
print(arr[5])
print(arr[5:8])
arr[5:8] = 12
print(arr)

arr_slice = arr[5:8]
print(arr_slice)

arr_slice[1] = 12345
print(arr)

arr_slice[:] = 64
arr

[0 1 2 3 4 5 6 7 8 9]
5
[5 6 7]
[ 0  1  2  3  4 12 12 12  8  9]
[12 12 12]
[    0     1     2     3     4    12 12345    12     8     9]


array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [34]:
arr_slice = arr[5:8]
arr_slice

array([12, 12, 12])

### 2d and 3d arrays

In [46]:
arr2d = np.array([[1, 2, 3], 
                  [4, 5, 6], 
                  [7, 8, 9]])
print(arr2d.shape)
print(arr2d[2])
print(arr2d[0][2])
print(arr2d[0, 2])

(3, 3)
[7 8 9]
3
3


In [45]:
arr3d = np.array([[[1, 2, 3], 
                   [4, 5, 6]], 
                  [[7, 8, 9], 
                   [10, 11, 12]]])
print(arr3d)
print()
print(arr3d.shape)
print()
print(arr3d[0])

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]

(2, 2, 3)

[[1 2 3]
 [4 5 6]]


In [48]:
old_values = arr3d[0].copy()
arr3d[0] = 42
print(arr3d)
arr3d[0] = old_values
arr3d

[[[42 42 42]
  [42 42 42]]

 [[ 7  8  9]
  [10 11 12]]]


array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [49]:
arr3d[1, 0]

array([7, 8, 9])

In [51]:
x = arr3d[1]
print(x)
x[0]

[[ 7  8  9]
 [10 11 12]]


array([7, 8, 9])

In [52]:
print(arr)
arr[1:6]

[ 0  1  2  3  4 64 64 64  8  9]


array([ 1,  2,  3,  4, 64])

In [58]:
print(arr2d)
print()
print(arr2d[:2])
print()
print(arr2d[:,:2])
print()
print(arr2d[:2, 1:])

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[1 2 3]
 [4 5 6]]

[[1 2]
 [4 5]
 [7 8]]

[[2 3]
 [5 6]]


In [60]:
lower_dim_slice = arr2d[1, :2]
print(lower_dim_slice)
lower_dim_slice.shape

[4 5]


(2,)

In [63]:
print(arr2d[:2, 2])
print(arr2d[:, :1])
arr2d[:2, 1:] = 0
print(arr2d)

[3 6]
[[1]
 [4]
 [7]]
[[1 0 0]
 [4 0 0]
 [7 8 9]]


### Masking

In [65]:
names = np.array(["Bob", "Joe", "Will", "Bob", "Will", "Joe", "Joe"])
data = np.array([[4, 7], [0, 2], [-5, 6], [0, 0], [1, 2], [-12, -4], [3, 4]])
print(names)
print(data)

['Bob' 'Joe' 'Will' 'Bob' 'Will' 'Joe' 'Joe']
[[  4   7]
 [  0   2]
 [ -5   6]
 [  0   0]
 [  1   2]
 [-12  -4]
 [  3   4]]


In [66]:
names == "Bob"

array([ True, False, False,  True, False, False, False])

In [67]:
data[names == "Bob"]

array([[4, 7],
       [0, 0]])

In [80]:
print(data[names == "Bob", 1:])
print(data[names == "Bob", 1])
print()
print(data[names == "Bob"][:,1])

[[7]
 [0]]
[7 0]

[7 0]


In [81]:
names != "Bob"
~(names == "Bob")
data[~(names == "Bob")]

array([[  0,   2],
       [ -5,   6],
       [  1,   2],
       [-12,  -4],
       [  3,   4]])

In [82]:
cond = names == "Bob"
data[~cond]

array([[  0,   2],
       [ -5,   6],
       [  1,   2],
       [-12,  -4],
       [  3,   4]])

In [83]:
mask = (names == "Bob") | (names == "Will")
mask
data[mask]

array([[ 4,  7],
       [-5,  6],
       [ 0,  0],
       [ 1,  2]])

In [84]:
data[data < 0] = 0
data

array([[4, 7],
       [0, 2],
       [0, 6],
       [0, 0],
       [1, 2],
       [0, 0],
       [3, 4]])

In [85]:
data[names != "Joe"] = 7
data

array([[7, 7],
       [0, 2],
       [7, 7],
       [7, 7],
       [7, 7],
       [0, 0],
       [3, 4]])

-------------------------

In [86]:
arr = np.zeros((8, 4))
for i in range(8):
    arr[i] = i
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [87]:
arr[[4, 3, 0, 6]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [88]:
arr[[-3, -5, -7]]

array([[5., 5., 5., 5.],
       [3., 3., 3., 3.],
       [1., 1., 1., 1.]])

In [91]:
arr = np.arange(32).reshape((8, 4))
print(arr)
arr[[1, 5, 7, 2], [0, 3, 1, 2]]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]


array([ 4, 23, 29, 10])

In [90]:
arr[[1, 5, 7, 2]][:, [0, 3, 1, 2]]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

In [92]:
arr[[1, 5, 7, 2], [0, 3, 1, 2]]
arr[[1, 5, 7, 2], [0, 3, 1, 2]] = 0
arr

array([[ 0,  1,  2,  3],
       [ 0,  5,  6,  7],
       [ 8,  9,  0, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22,  0],
       [24, 25, 26, 27],
       [28,  0, 30, 31]])

In [95]:
arr = np.arange(15).reshape((3, 5))
print(arr)
arr.T

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [94]:
arr = np.array([[0, 1, 0], [1, 2, -2], [6, 3, 2], [-1, 0, -1], [1, 0, 1]])
print(arr)
# dot product
np.dot(arr.T, arr)

[[ 0  1  0]
 [ 1  2 -2]
 [ 6  3  2]
 [-1  0 -1]
 [ 1  0  1]]


array([[39, 20, 12],
       [20, 14,  2],
       [12,  2, 10]])

In [96]:
# element-wise matrix multiplication
arr.T @ arr

array([[125, 140, 155, 170, 185],
       [140, 158, 176, 194, 212],
       [155, 176, 197, 218, 239],
       [170, 194, 218, 242, 266],
       [185, 212, 239, 266, 293]])

In [99]:
# element-wise matrix multiplication
np.matmul(arr.T, arr)

array([[125, 140, 155, 170, 185],
       [140, 158, 176, 194, 212],
       [155, 176, 197, 218, 239],
       [170, 194, 218, 242, 266],
       [185, 212, 239, 266, 293]])