# NumPy Basics: Arrays and Vectorized Computation

In [3]:
import numpy as np
np.random.seed(12345)
import matplotlib.pyplot as plt
plt.rc("figure", figsize=(10, 6))
np.set_printoptions(precision=4, suppress=True)

In [4]:
import numpy as np

my_arr = np.arange(1_000_000)
my_list = list(range(1_000_000))

%timeit my_arr2 = my_arr * 2
%timeit my_list2 = [x * 2 for x in my_list]

1.59 ms ± 18.7 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
75.7 ms ± 730 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [7]:
import numpy as np
data = np.array([[1.5, -0.1, 3], [0, -3, 6.5]])
print(data)
print()
print(data * 10)
print()
print(data + data)
print()
print(data.shape) 
print()
print(data.dtype)

[[ 1.5 -0.1  3. ]
 [ 0.  -3.   6.5]]

[[ 15.  -1.  30.]
 [  0. -30.  65.]]

[[ 3.  -0.2  6. ]
 [ 0.  -6.  13. ]]

(2, 3)

float64


In [11]:
data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1)
print(arr1)

data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)
print(arr2)
print()
print(arr2.ndim, arr2.shape)
print(arr1.dtype, arr2.dtype)

[6.  7.5 8.  0.  1. ]
[[1 2 3 4]
 [5 6 7 8]]

2 (2, 4)
float64 int64


In [19]:
np.zeros(10)
np.zeros((3, 6))
em = np.empty((2, 3, 2))

print(em[1][2] is None)

np.arange(15)

False


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [21]:
arr1 = np.array([1, 2, 3], dtype=np.float64)
arr2 = np.array([1, 2, 3], dtype=np.int32)
print(arr1.dtype, arr2.dtype)

arr = np.array([1, 2, 3, 4, 5])
print(arr.dtype)
float_arr = arr.astype(np.float64)
print(float_arr)
print(float_arr.dtype)

float64 int32
int64
[1. 2. 3. 4. 5.]
float64


In [23]:
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])
print(arr)
arr.astype(np.int32)

[ 3.7 -1.2 -2.6  0.5 12.9 10.1]


array([ 3, -1, -2,  0, 12, 10], dtype=int32)

In [24]:
numeric_strings = np.array(["1.25", "-9.6", "42"], dtype=np.string_)
numeric_strings.astype(float)

array([ 1.25, -9.6 , 42.  ])

In [25]:
int_array = np.arange(10)
calibers = np.array([.22, .270, .357, .380, .44, .50], dtype=np.float64)
int_array.astype(calibers.dtype)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])