# Data Cleaning and Preparation

In [1]:
import numpy as np
import pandas as pd
PREVIOUS_MAX_ROWS = pd.options.display.max_rows
pd.options.display.max_rows = 25
pd.options.display.max_columns = 20
pd.options.display.max_colwidth = 82
np.random.seed(12345)
import matplotlib.pyplot as plt
plt.rc("figure", figsize=(10, 6))
np.set_printoptions(precision=4, suppress=True)

In [2]:
float_data = pd.Series([1.2, -3.5, np.nan, 0])

print(float_data)

print(float_data.isna())

0    1.2
1   -3.5
2    NaN
3    0.0
dtype: float64
0    False
1    False
2     True
3    False
dtype: bool


In [3]:
string_data = pd.Series(["aardvark", np.nan, None, "avocado"])
print(string_data)
print(string_data.isna())
float_data = pd.Series([1, 2, None], dtype='float64')
print(float_data)
print(float_data.isna())

0    aardvark
1         NaN
2        None
3     avocado
dtype: object
0    False
1     True
2     True
3    False
dtype: bool
0    1.0
1    2.0
2    NaN
dtype: float64
0    False
1    False
2     True
dtype: bool


In [4]:
data = pd.Series([1, np.nan, 3.5, np.nan, 7])
print(data.dropna())
print(data[data.notna()])

0    1.0
2    3.5
4    7.0
dtype: float64
0    1.0
2    3.5
4    7.0
dtype: float64


In [5]:
data = pd.DataFrame([[1., 6.5, 3.], [1., np.nan, np.nan],
                     [np.nan, np.nan, np.nan], [np.nan, 6.5, 3.]])
print(data)
print(data.dropna())

print(data.dropna(how="all"))

data[4] = np.nan
print(data)
print(data.dropna(axis="columns", how="all"))

     0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0
     0    1    2
0  1.0  6.5  3.0
     0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
3  NaN  6.5  3.0
     0    1    2   4
0  1.0  6.5  3.0 NaN
1  1.0  NaN  NaN NaN
2  NaN  NaN  NaN NaN
3  NaN  6.5  3.0 NaN
     0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0


In [9]:
df = pd.DataFrame(np.random.standard_normal((7, 3)))
df.iloc[:4, 1] = np.nan
df.iloc[:2, 2] = np.nan
print(df)
print()
print(df.dropna())
print()
df.dropna(thresh=2)

          0         1         2
0  0.670216       NaN       NaN
1 -0.023493       NaN       NaN
2 -1.218302       NaN  1.074623
3  0.723642       NaN  1.001543
4 -0.503087 -0.622274 -0.921169
5 -0.726213  0.222896  0.051316
6 -1.157719  0.816707  0.433610

          0         1         2
4 -0.503087 -0.622274 -0.921169
5 -0.726213  0.222896  0.051316
6 -1.157719  0.816707  0.433610



0         1         2
2 -1.218302       NaN  1.074623
3  0.723642       NaN  1.001543
4 -0.503087 -0.622274 -0.921169
5 -0.726213  0.222896  0.051316
6 -1.157719  0.816707  0.433610

In [11]:
print(df.fillna(0))
print()
print(df.fillna({1: 0.5, 2: 0}))

          0         1         2
0  0.670216  0.000000  0.000000
1 -0.023493  0.000000  0.000000
2 -1.218302  0.000000  1.074623
3  0.723642  0.000000  1.001543
4 -0.503087 -0.622274 -0.921169
5 -0.726213  0.222896  0.051316
6 -1.157719  0.816707  0.433610

          0         1         2
0  0.670216  0.500000  0.000000
1 -0.023493  0.500000  0.000000
2 -1.218302  0.500000  1.074623
3  0.723642  0.500000  1.001543
4 -0.503087 -0.622274 -0.921169
5 -0.726213  0.222896  0.051316
6 -1.157719  0.816707  0.433610


In [12]:
df = pd.DataFrame(np.random.standard_normal((6, 3)))
df.iloc[2:, 1] = np.nan
df.iloc[4:, 2] = np.nan
print(df)
print()
print(df.fillna(method="ffill"))
print()
print(df.fillna(method="ffill", limit=2))

          0         1         2
0  1.010737  1.824875 -0.997518
1  0.850591 -0.131578  0.912414
2  0.188211       NaN -0.114928
3  2.003697       NaN  0.795253
4  0.118110       NaN       NaN
5  0.152677       NaN       NaN

          0         1         2
0  1.010737  1.824875 -0.997518
1  0.850591 -0.131578  0.912414
2  0.188211 -0.131578 -0.114928
3  2.003697 -0.131578  0.795253
4  0.118110 -0.131578  0.795253
5  0.152677 -0.131578  0.795253

          0         1         2
0  1.010737  1.824875 -0.997518
1  0.850591 -0.131578  0.912414
2  0.188211 -0.131578 -0.114928
3  2.003697 -0.131578  0.795253
4  0.118110       NaN  0.795253
5  0.152677       NaN  0.795253


In [13]:
data = pd.Series([1., np.nan, 3.5, np.nan, 7])
data.fillna(data.mean())

0    1.000000
1    3.833333
2    3.500000
3    3.833333
4    7.000000
dtype: float64

In [17]:
data = pd.DataFrame({"k1": ["one", "two"] * 3 + ["two"],
                     "k2": [1, 1, 2, 3, 3, 4, 4]})
print(data)
print()
print(data.duplicated())
print()
print(data.drop_duplicates())

    k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4
6  two   4

0    False
1    False
2    False
3    False
4    False
5    False
6     True
dtype: bool

    k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4


In [18]:
data["v1"] = range(7)
print(data)
data.drop_duplicates(subset=["k1"])

    k1  k2  v1
0  one   1   0
1  two   1   1
2  one   2   2
3  two   3   3
4  one   3   4
5  two   4   5
6  two   4   6


k1  k2  v1
0  one   1   0
1  two   1   1

In [19]:
data.drop_duplicates(["k1", "k2"], keep="last")

k1  k2  v1
0  one   1   0
1  two   1   1
2  one   2   2
3  two   3   3
4  one   3   4
6  two   4   6

In [20]:
data = pd.DataFrame({"food": ["bacon", "pulled pork", "bacon",
                              "pastrami", "corned beef", "bacon",
                              "pastrami", "honey ham", "nova lox"],
                     "ounces": [4, 3, 12, 6, 7.5, 8, 3, 5, 6]})
data

food  ounces
0        bacon     4.0
1  pulled pork     3.0
2        bacon    12.0
3     pastrami     6.0
4  corned beef     7.5
5        bacon     8.0
6     pastrami     3.0
7    honey ham     5.0
8     nova lox     6.0

In [22]:
meat_to_animal = {
  "bacon": "pig",
  "pulled pork": "pig",
  "pastrami": "cow",
  "corned beef": "cow",
  "honey ham": "pig",
  "nova lox": "salmon"
}

data["animal"] = data["food"].map(meat_to_animal)
data

food  ounces  animal
0        bacon     4.0     pig
1  pulled pork     3.0     pig
2        bacon    12.0     pig
3     pastrami     6.0     cow
4  corned beef     7.5     cow
5        bacon     8.0     pig
6     pastrami     3.0     cow
7    honey ham     5.0     pig
8     nova lox     6.0  salmon

In [23]:
def get_animal(x):
    return meat_to_animal[x]
data["food"].map(get_animal)

0       pig
1       pig
2       pig
3       cow
4       cow
5       pig
6       cow
7       pig
8    salmon
Name: food, dtype: object

In [25]:
data = pd.Series([1., -999., 2., -999., -1000., 3.])
print(data)
print()
print(data.replace(-999, np.nan))
print()
print(data.replace([-999, -1000], np.nan))
print()
print(data.replace([-999, -1000], [np.nan, 0]))
print()
print(data.replace({-999: np.nan, -1000: 0}))

0       1.0
1    -999.0
2       2.0
3    -999.0
4   -1000.0
5       3.0
dtype: float64

0       1.0
1       NaN
2       2.0
3       NaN
4   -1000.0
5       3.0
dtype: float64

0    1.0
1    NaN
2    2.0
3    NaN
4    NaN
5    3.0
dtype: float64

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64


In [30]:
data = pd.DataFrame(np.arange(12).reshape((3, 4)),
                    index=["Ohio", "Colorado", "New York"],
                    columns=["one", "two", "three", "four"])
print(data)

def transform(x):
    return x[:4].upper()

data.index.map(transform)

          one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
New York    8    9     10    11


Index(['OHIO', 'COLO', 'NEW '], dtype='object')

In [32]:
data.index = data.index.map(transform)
print(data)
print()
print(data.rename(index=str.title, columns=str.upper))
print()
print(data.rename(index={"OHIO": "INDIANA"},
            columns={"three": "peekaboo"}))
data

      one  two  three  four
OHIO    0    1      2     3
COLO    4    5      6     7
NEW     8    9     10    11

      ONE  TWO  THREE  FOUR
Ohio    0    1      2     3
Colo    4    5      6     7
New     8    9     10    11

         one  two  peekaboo  four
INDIANA    0    1         2     3
COLO       4    5         6     7
NEW        8    9        10    11


one  two  three  four
OHIO    0    1      2     3
COLO    4    5      6     7
NEW     8    9     10    11

In [33]:
ages = [20, 22, 25, 27, 21, 23, 37, 31, 61, 45, 41, 32]
bins = [18, 25, 35, 60, 100]
age_categories = pd.cut(ages, bins)
age_categories

[(18, 25], (18, 25], (18, 25], (25, 35], (18, 25], ..., (25, 35], (60, 100], (35, 60], (35, 60], (25, 35]]
Length: 12
Categories (4, interval[int64]): [(18, 25] < (25, 35] < (35, 60] < (60, 100]]

In [35]:
print(age_categories.codes)
print()
print(age_categories.categories)
print()
print(age_categories.categories[0])
print()
print(pd.value_counts(age_categories))
pd.cut(ages, bins, right=False)

[0 0 0 1 0 0 2 1 3 2 2 1]

IntervalIndex([(18, 25], (25, 35], (35, 60], (60, 100]],
              closed='right',
              dtype='interval[int64]')

(18, 25]

(18, 25]     5
(35, 60]     3
(25, 35]     3
(60, 100]    1
dtype: int64


[[18, 25), [18, 25), [25, 35), [25, 35), [18, 25), ..., [25, 35), [60, 100), [35, 60), [35, 60), [25, 35)]
Length: 12
Categories (4, interval[int64]): [[18, 25) < [25, 35) < [35, 60) < [60, 100)]

In [36]:
group_names = ["Youth", "YoungAdult", "MiddleAged", "Senior"]
pd.cut(ages, bins, labels=group_names)

['Youth', 'Youth', 'Youth', 'YoungAdult', 'Youth', ..., 'YoungAdult', 'Senior', 'MiddleAged', 'MiddleAged', 'YoungAdult']
Length: 12
Categories (4, object): ['Youth' < 'YoungAdult' < 'MiddleAged' < 'Senior']

In [37]:
data = np.random.uniform(size=20)
pd.cut(data, 4, precision=2)

[(0.014, 0.24], (0.46, 0.69], (0.46, 0.69], (0.014, 0.24], (0.69, 0.91], ..., (0.014, 0.24], (0.014, 0.24], (0.69, 0.91], (0.24, 0.46], (0.46, 0.69]]
Length: 20
Categories (4, interval[float64]): [(0.014, 0.24] < (0.24, 0.46] < (0.46, 0.69] < (0.69, 0.91]]

In [38]:
data = np.random.standard_normal(1000)
quartiles = pd.qcut(data, 4, precision=2)
quartiles
pd.value_counts(quartiles)

(0.6, 3.93]        250
(-0.031, 0.6]      250
(-0.68, -0.031]    250
(-2.96, -0.68]     250
dtype: int64

In [39]:
pd.qcut(data, [0, 0.1, 0.5, 0.9, 1.]).value_counts()

(-2.9499999999999997, -1.176]    100
(-1.176, -0.0309]                400
(-0.0309, 1.289]                 400
(1.289, 3.928]                   100
dtype: int64

In [40]:
data = pd.DataFrame(np.random.standard_normal((1000, 4)))
data.describe()

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean     -0.046809     0.047671     0.028549    -0.013509
std       0.998033     1.001893     1.010125     0.997685
min      -3.428254    -3.645860    -3.184377    -3.745356
25%      -0.740152    -0.600254    -0.612162    -0.700274
50%      -0.086309     0.047101    -0.005700    -0.033738
75%       0.625698     0.750195     0.695298     0.692355
max       3.366626     2.653656     3.525865     2.735527

In [41]:
col = data[2]
col[col.abs() > 3]

44     3.260383
219   -3.056990
306   -3.184377
766    3.525865
Name: 2, dtype: float64

In [42]:
data[(data.abs() > 3).any(axis="columns")]

0         1         2         3
25  -2.315555  0.457246 -0.025907 -3.399312
44   0.050188  1.951312  3.260383  0.963301
120  0.146326  0.508391 -0.196713 -3.745356
219 -0.293333 -0.242459 -3.056990  1.918403
243 -3.428254 -0.296336 -0.439938 -0.867165
306  0.275144  1.179227 -3.184377  1.369891
528 -0.362528 -3.548824  1.553205 -2.186301
620  3.366626 -2.372214  0.851010  1.332846
766 -0.658090 -0.207434  3.525865  0.283070
787  0.599947 -3.645860  0.255475 -0.549574

In [43]:
data[data.abs() > 3] = np.sign(data) * 3
data.describe()

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean     -0.046747     0.048866     0.028004    -0.012364
std       0.995481     0.997887     1.006891     0.993888
min      -3.000000    -3.000000    -3.000000    -3.000000
25%      -0.740152    -0.600254    -0.612162    -0.700274
50%      -0.086309     0.047101    -0.005700    -0.033738
75%       0.625698     0.750195     0.695298     0.692355
max       3.000000     2.653656     3.000000     2.735527

In [44]:
np.sign(data).head()

0    1    2    3
0 -1.0  1.0  1.0 -1.0
1  1.0  1.0  1.0 -1.0
2  1.0  1.0  1.0 -1.0
3 -1.0  1.0  1.0  1.0
4 -1.0 -1.0 -1.0 -1.0

In [47]:
df = pd.DataFrame(np.arange(5 * 7).reshape((5, 7)))
print(df)
print()
sampler = np.random.permutation(5)
print(sampler)

    0   1   2   3   4   5   6
0   0   1   2   3   4   5   6
1   7   8   9  10  11  12  13
2  14  15  16  17  18  19  20
3  21  22  23  24  25  26  27
4  28  29  30  31  32  33  34

[4 2 0 3 1]


In [46]:
print(df.take(sampler))
print()
print(df.iloc[sampler])

    0   1   2   3   4   5   6
1   7   8   9  10  11  12  13
0   0   1   2   3   4   5   6
4  28  29  30  31  32  33  34
3  21  22  23  24  25  26  27
2  14  15  16  17  18  19  20

    0   1   2   3   4   5   6
1   7   8   9  10  11  12  13
0   0   1   2   3   4   5   6
4  28  29  30  31  32  33  34
3  21  22  23  24  25  26  27
2  14  15  16  17  18  19  20


In [49]:
column_sampler = np.random.permutation(7)
print(column_sampler)
df.take(column_sampler, axis="columns")

[4 0 3 2 1 6 5]


4   0   3   2   1   6   5
0   4   0   3   2   1   6   5
1  11   7  10   9   8  13  12
2  18  14  17  16  15  20  19
3  25  21  24  23  22  27  26
4  32  28  31  30  29  34  33

In [50]:
df.sample(n=3)

0   1   2   3   4   5   6
0   0   1   2   3   4   5   6
1   7   8   9  10  11  12  13
4  28  29  30  31  32  33  34

In [51]:
choices = pd.Series([5, 7, -1, 6, 4])
choices.sample(n=10, replace=True)

4    4
1    7
4    4
3    6
1    7
4    4
4    4
3    6
2   -1
1    7
dtype: int64

In [52]:
df = pd.DataFrame({"key": ["b", "b", "a", "c", "a", "b"],
                   "data1": range(6)})
print(df)
pd.get_dummies(df["key"])

  key  data1
0   b      0
1   b      1
2   a      2
3   c      3
4   a      4
5   b      5


a  b  c
0  0  1  0
1  0  1  0
2  1  0  0
3  0  0  1
4  1  0  0
5  0  1  0

In [53]:
dummies = pd.get_dummies(df["key"], prefix="key")
df_with_dummy = df[["data1"]].join(dummies)
df_with_dummy

data1  key_a  key_b  key_c
0      0      0      1      0
1      1      0      1      0
2      2      1      0      0
3      3      0      0      1
4      4      1      0      0
5      5      0      1      0

In [54]:
mnames = ["movie_id", "title", "genres"]
movies = pd.read_table("datasets/movielens/movies.dat", sep="::",
                       header=None, names=mnames, engine="python")
movies[:10]

movie_id                               title                        genres
0         1                    Toy Story (1995)   Animation|Children's|Comedy
1         2                      Jumanji (1995)  Adventure|Children's|Fantasy
2         3             Grumpier Old Men (1995)                Comedy|Romance
3         4            Waiting to Exhale (1995)                  Comedy|Drama
4         5  Father of the Bride Part II (1995)                        Comedy
5         6                         Heat (1995)         Action|Crime|Thriller
6         7                      Sabrina (1995)                Comedy|Romance
7         8                 Tom and Huck (1995)          Adventure|Children's
8         9                 Sudden Death (1995)                        Action
9        10                    GoldenEye (1995)     Action|Adventure|Thriller

In [55]:
dummies = movies["genres"].str.get_dummies("|")
dummies.iloc[:10, :6]

Action  Adventure  Animation  Children's  Comedy  Crime
0       0          0          1           1       1      0
1       0          1          0           1       0      0
2       0          0          0           0       1      0
3       0          0          0           0       1      0
4       0          0          0           0       1      0
5       1          0          0           0       0      1
6       0          0          0           0       1      0
7       0          1          0           1       0      0
8       1          0          0           0       0      0
9       1          1          0           0       0      0

In [56]:
movies_windic = movies.join(dummies.add_prefix("Genre_"))
movies_windic.iloc[0]

movie_id                                       1
title                           Toy Story (1995)
genres               Animation|Children's|Comedy
Genre_Action                                   0
Genre_Adventure                                0
Genre_Animation                                1
Genre_Children's                               1
Genre_Comedy                                   1
Genre_Crime                                    0
Genre_Documentary                              0
Genre_Drama                                    0
Genre_Fantasy                                  0
Genre_Film-Noir                                0
Genre_Horror                                   0
Genre_Musical                                  0
Genre_Mystery                                  0
Genre_Romance                                  0
Genre_Sci-Fi                                   0
Genre_Thriller                                 0
Genre_War                                      0
Genre_Western       

In [57]:
np.random.seed(12345) # to make the example repeatable
values = np.random.uniform(size=10)
values
bins = [0, 0.2, 0.4, 0.6, 0.8, 1]
pd.get_dummies(pd.cut(values, bins))

(0.0, 0.2]  (0.2, 0.4]  (0.4, 0.6]  (0.6, 0.8]  (0.8, 1.0]
0           0           0           0           0           1
1           0           1           0           0           0
2           1           0           0           0           0
3           0           1           0           0           0
4           0           0           1           0           0
5           0           0           1           0           0
6           0           0           0           0           1
7           0           0           0           1           0
8           0           0           0           1           0
9           0           0           0           1           0

In [58]:
s = pd.Series([1, 2, 3, None])
s
s.dtype

dtype('float64')

In [59]:
s = pd.Series([1, 2, 3, None], dtype=pd.Int64Dtype())
s
s.isna()
s.dtype

Int64Dtype()

In [60]:
s[3]
s[3] is pd.NA

True

In [62]:
s = pd.Series([1, 2, 3, None], dtype="Int64")
s

0       1
1       2
2       3
3    <NA>
dtype: Int64

In [63]:
s = pd.Series(['one', 'two', None, 'three'], dtype=pd.StringDtype())
s

0      one
1      two
2     <NA>
3    three
dtype: string

In [64]:
df = pd.DataFrame({"A": [1, 2, None, 4],
                   "B": ["one", "two", "three", None],
                   "C": [False, None, False, True]})
print(df)
df["A"] = df["A"].astype("Int64")
df["B"] = df["B"].astype("string")
df["C"] = df["C"].astype("boolean")
print(df)

     A      B      C
0  1.0    one  False
1  2.0    two   None
2  NaN  three  False
3  4.0   None   True
      A      B      C
0     1    one  False
1     2    two   <NA>
2  <NA>  three  False
3     4   <NA>   True


In [65]:
val = "a,b,  guido"
val.split(",")

['a', 'b', '  guido']

In [66]:
pieces = [x.strip() for x in val.split(",")]
pieces

['a', 'b', 'guido']

In [67]:
first, second, third = pieces
first + "::" + second + "::" + third

'a::b::guido'

In [68]:
"::".join(pieces)

'a::b::guido'

In [76]:
print("guido" in val)
print(val.index(","))
print(val.find(":"))
#val.index(":") # -> substring not found
print(val.count(","))
print()
print(val.replace(",", "::"))
print(val.replace(",", ""))

True
1
-1
2

a::b::  guido
ab  guido


### Regular Expressions

In [77]:
import re
text = "foo    bar\t baz  \tqux"
re.split(r"\s+", text)

['foo', 'bar', 'baz', 'qux']

In [78]:
regex = re.compile(r"\s+")
regex.split(text)

['foo', 'bar', 'baz', 'qux']

In [79]:
regex.findall(text)

['    ', '\t ', '  \t']

In [81]:
text = """Dave dave@google.com
Steve steve@gmail.com
Rob rob@gmail.com
Ryan ryan@yahoo.com"""
pattern = r"[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}"

# re.IGNORECASE makes the regex case insensitive
regex = re.compile(pattern, flags=re.IGNORECASE)

regex.findall(text)

['dave@google.com', 'steve@gmail.com', 'rob@gmail.com', 'ryan@yahoo.com']

In [83]:
m = regex.search(text)
print(m)
text[m.start():m.end()]

<_sre.SRE_Match object; span=(5, 20), match='dave@google.com'>


'dave@google.com'

In [84]:
print(regex.match(text))

None


In [85]:
print(regex.sub("REDACTED", text))

Dave REDACTED
Steve REDACTED
Rob REDACTED
Ryan REDACTED


In [86]:
pattern = r"([A-Z0-9._%+-]+)@([A-Z0-9.-]+)\.([A-Z]{2,4})"
regex = re.compile(pattern, flags=re.IGNORECASE)

In [87]:
m = regex.match("wesm@bright.net")
m.groups()

('wesm', 'bright', 'net')

In [88]:
regex.findall(text)

[('dave', 'google', 'com'),
 ('steve', 'gmail', 'com'),
 ('rob', 'gmail', 'com'),
 ('ryan', 'yahoo', 'com')]

In [89]:
print(regex.sub(r"Username: \1, Domain: \2, Suffix: \3", text))

Dave Username: dave, Domain: google, Suffix: com
Steve Username: steve, Domain: gmail, Suffix: com
Rob Username: rob, Domain: gmail, Suffix: com
Ryan Username: ryan, Domain: yahoo, Suffix: com


In [90]:
data = {"Dave": "dave@google.com", "Steve": "steve@gmail.com",
        "Rob": "rob@gmail.com", "Wes": np.nan}
data = pd.Series(data)
print(data)
data.isna()

Dave     dave@google.com
Steve    steve@gmail.com
Rob        rob@gmail.com
Wes                  NaN
dtype: object


Dave     False
Steve    False
Rob      False
Wes       True
dtype: bool

In [92]:
data.str.contains("gmail")

data_as_string_ext = data.astype('string')
data_as_string_ext
data_as_string_ext.str.contains("gmail")

Dave     False
Steve     True
Rob       True
Wes       <NA>
dtype: boolean

In [93]:
pattern = r"([A-Z0-9._%+-]+)@([A-Z0-9.-]+)\.([A-Z]{2,4})"
data.str.findall(pattern, flags=re.IGNORECASE)

Dave     [(dave, google, com)]
Steve    [(steve, gmail, com)]
Rob        [(rob, gmail, com)]
Wes                        NaN
dtype: object

In [94]:
matches = data.str.findall(pattern, flags=re.IGNORECASE).str[0]
matches
matches.str.get(1)

Dave     google
Steve     gmail
Rob       gmail
Wes         NaN
dtype: object

In [95]:
data.str[:5]

Dave     dave@
Steve    steve
Rob      rob@g
Wes        NaN
dtype: object

In [96]:
data.str.extract(pattern, flags=re.IGNORECASE)

0       1    2
Dave    dave  google  com
Steve  steve   gmail  com
Rob      rob   gmail  com
Wes      NaN     NaN  NaN

In [97]:
values = pd.Series(['apple', 'orange', 'apple',
                    'apple'] * 2)
values
pd.unique(values)
pd.value_counts(values)

apple     6
orange    2
dtype: int64

In [98]:
values = pd.Series([0, 1, 0, 0] * 2)
dim = pd.Series(['apple', 'orange'])
values
dim

0     apple
1    orange
dtype: object

In [99]:
dim.take(values)

0     apple
1    orange
0     apple
0     apple
0     apple
1    orange
0     apple
0     apple
dtype: object

In [100]:
fruits = ['apple', 'orange', 'apple', 'apple'] * 2
N = len(fruits)
rng = np.random.default_rng(seed=12345)
df = pd.DataFrame({'fruit': fruits,
                   'basket_id': np.arange(N),
                   'count': rng.integers(3, 15, size=N),
                   'weight': rng.uniform(0, 4, size=N)},
                  columns=['basket_id', 'fruit', 'count', 'weight'])
df

basket_id   fruit  count    weight
0          0   apple     11  1.564438
1          1  orange      5  1.331256
2          2   apple     12  2.393235
3          3   apple      6  0.746937
4          4   apple      5  2.691024
5          5  orange     12  3.767211
6          6   apple     10  0.992983
7          7   apple     11  3.795525

In [102]:
fruit_cat = df['fruit'].astype('category')
fruit_cat

0     apple
1    orange
2     apple
3     apple
4     apple
5    orange
6     apple
7     apple
Name: fruit, dtype: category
Categories (2, object): ['apple', 'orange']

In [104]:
c = fruit_cat.array
type(c)

print(c.categories)
print(c.codes)

Index(['apple', 'orange'], dtype='object')
[0 1 0 0 0 1 0 0]


In [105]:
dict(enumerate(c.categories))

{0: 'apple', 1: 'orange'}

In [106]:
df['fruit'] = df['fruit'].astype('category')
df["fruit"]

0     apple
1    orange
2     apple
3     apple
4     apple
5    orange
6     apple
7     apple
Name: fruit, dtype: category
Categories (2, object): ['apple', 'orange']

In [107]:
my_categories = pd.Categorical(['foo', 'bar', 'baz', 'foo', 'bar'])
my_categories

['foo', 'bar', 'baz', 'foo', 'bar']
Categories (3, object): ['bar', 'baz', 'foo']

In [108]:
categories = ['foo', 'bar', 'baz']
codes = [0, 1, 2, 0, 0, 1]
my_cats_2 = pd.Categorical.from_codes(codes, categories)
my_cats_2

['foo', 'bar', 'baz', 'foo', 'foo', 'bar']
Categories (3, object): ['foo', 'bar', 'baz']

In [110]:
ordered_cat = pd.Categorical.from_codes(codes, categories,
                                        ordered=True)
print(ordered_cat)

print(my_cats_2.as_ordered())

['foo', 'bar', 'baz', 'foo', 'foo', 'bar']
Categories (3, object): ['foo' < 'bar' < 'baz']
['foo', 'bar', 'baz', 'foo', 'foo', 'bar']
Categories (3, object): ['foo' < 'bar' < 'baz']


In [111]:
rng = np.random.default_rng(seed=12345)
draws = rng.standard_normal(1000)
draws[:5]

array([-1.4238,  1.2637, -0.8707, -0.2592, -0.0753])

In [112]:
bins = pd.qcut(draws, 4)
bins

[(-3.121, -0.675], (0.687, 3.211], (-3.121, -0.675], (-0.675, 0.0134], (-0.675, 0.0134], ..., (0.0134, 0.687], (0.0134, 0.687], (-0.675, 0.0134], (0.0134, 0.687], (-0.675, 0.0134]]
Length: 1000
Categories (4, interval[float64]): [(-3.121, -0.675] < (-0.675, 0.0134] < (0.0134, 0.687] < (0.687, 3.211]]

In [113]:
bins = pd.qcut(draws, 4, labels=['Q1', 'Q2', 'Q3', 'Q4'])
bins
bins.codes[:10]

array([0, 3, 0, 1, 1, 0, 0, 2, 2, 0], dtype=int8)

In [116]:
bins = pd.Series(bins, name='quartile')
results = (pd.Series(draws)
           .groupby(bins)
           .agg(['count', 'min', 'max'])
           .reset_index())
print(results)

results['quartile']

  quartile  count       min       max
0       Q1    250 -3.119609 -0.678494
1       Q2    250 -0.673305  0.008009
2       Q3    250  0.018753  0.686183
3       Q4    250  0.688282  3.211418


0    Q1
1    Q2
2    Q3
3    Q4
Name: quartile, dtype: category
Categories (4, object): ['Q1' < 'Q2' < 'Q3' < 'Q4']

In [119]:
N = 10_000_000
labels = pd.Series(['foo', 'bar', 'baz', 'qux'] * (N // 4))

categories = labels.astype('category')

print(labels.memory_usage(deep=True))
print(categories.memory_usage(deep=True))

600000128
10000528


In [120]:
%time _ = labels.astype('category')

CPU times: user 358 ms, sys: 23.4 ms, total: 381 ms
Wall time: 413 ms


In [121]:
%timeit labels.value_counts()
%timeit categories.value_counts()

690 ms ± 90.3 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
39.5 ms ± 997 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [124]:
s = pd.Series(['a', 'b', 'c', 'd'] * 2)
cat_s = s.astype('category')
print(cat_s)
print()
print(cat_s.cat.codes)
print()
print(cat_s.cat.categories)

0    a
1    b
2    c
3    d
4    a
5    b
6    c
7    d
dtype: category
Categories (4, object): ['a', 'b', 'c', 'd']

0    0
1    1
2    2
3    3
4    0
5    1
6    2
7    3
dtype: int8

Index(['a', 'b', 'c', 'd'], dtype='object')


In [125]:
actual_categories = ['a', 'b', 'c', 'd', 'e']
cat_s2 = cat_s.cat.set_categories(actual_categories)
print(cat_s2)
print()
print(cat_s.value_counts())
print()
print(cat_s2.value_counts())

0    a
1    b
2    c
3    d
4    a
5    b
6    c
7    d
dtype: category
Categories (5, object): ['a', 'b', 'c', 'd', 'e']

d    2
c    2
b    2
a    2
dtype: int64

d    2
c    2
b    2
a    2
e    0
dtype: int64


In [127]:
cat_s3 = cat_s[cat_s.isin(['a', 'b'])]
cat_s3
cat_s3.cat.remove_unused_categories()

cat_s = pd.Series(['a', 'b', 'c', 'd'] * 2, dtype='category')
pd.get_dummies(cat_s)

a  b  c  d
0  1  0  0  0
1  0  1  0  0
2  0  0  1  0
3  0  0  0  1
4  1  0  0  0
5  0  1  0  0
6  0  0  1  0
7  0  0  0  1

In [128]:
pd.options.display.max_rows = PREVIOUS_MAX_ROWS

# Data Wrangling: Join, Combine, and Reshape

In [129]:
import numpy as np
import pandas as pd
pd.options.display.max_rows = 20
pd.options.display.max_colwidth = 80
pd.options.display.max_columns = 20
np.random.seed(12345)
import matplotlib.pyplot as plt
plt.rc("figure", figsize=(10, 6))
np.set_printoptions(precision=4, suppress=True)